asc 4 - added routing and map page
Shaybush/chat_browsers pull request #4
Opened 2023-11-13 16:22 UTC by avivt10

2023-11-13 16:24 UTC, Shaybush commented on client_react/src/App.jsx
> +import HomePage from "../src/components/HomePage/HomePage";
1. why did you change that ?
2. use just one /homePage

2023-11-13 16:25 UTC, Shaybush commented on client_react/src/AppRoutes.jsx
> +import _Loader from "./components/Loader/_Loader";
use single call /loader with lowerase

2023-11-13 16:27 UTC, Shaybush commented on client_react/src/AppRoutes.jsx
> +    const Chat = React.lazy(() => import("./components/HomePage/HomePage"));
why home page declare twice?

2023-11-13 16:28 UTC, Shaybush commented on client_react/src/components/DashboardPage/Dashboard.jsx
> +    existUser = null;
use set

2023-11-13 16:29 UTC, Shaybush commented on client_react/src/components/DashboardPage/Dashboard.jsx
> +  // }
delete

2023-11-13 16:33 UTC, Shaybush requested changes
fix please

2023-11-14 09:02 UTC, avivt10 commented on client_react/src/components/DashboardPage/Dashboard.jsx
> +    existUser = null;
Done.

2023-11-16 08:30 UTC, Shaybush approved these changes

2023-11-16 10:12 UTC, merged